#!/bin/bash


if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Installing commandline tools..."
  xcode-select --install

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  brew analytics off
fi
