#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install --cack ghostty
  brew install --cack brave-browser
  brew install --cack spotify
  brew install --cack nikitabobko/tap/aerospace
  brew install --cack font-fira-code-nerd-font
  brew install --cack alfred
fi
