#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install git neovim tmux lua luajit luarocks fzf yazi ripgrep make zsh-autosuggestions zsh-syntax-highlighting
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  sudo apt-get install neovim tmux lua luajit luarocks fzf
fi

